project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
    - "!working/archive/*"    
  output-dir: ../docs/

website:  
  title: "LMM/MLM"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - 01_clustered.qmd
      - 02_lmm.qmd
      - 03_inference.qmd
      - 04_log.qmd
      - 05_long.qmd
      - 06_poly.qmd
      - 07_ranef.qmd
      - 08_modelbuilding.qmd
      - 09_assump.qmd
      - 10_centering.qmd
      - 11_writing.qmd
      - section: "Additional Docs"
        contents:
          - 00_lm_assumpt.qmd
          - lvp.qmd
          - 00_datasets.qmd

format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


