{
  "hash": "a8931a0f0e91db70c86c3d7c257165cd",
  "result": {
    "markdown": "---\ntitle: \"10: Centering\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n:::lo\nThis reading:  \n\n- Centering and scaling predictors in single level regression\n- Group-mean centering predictors in the multilevel model to separate out \"within\"-group effects from \"between\"-group effects\n- Optional: contextual effects and the Mundlak model\n\n:::\n\n\n\n## Centering predictors in `lm()`\n\nThere are lots of ways we can transform a variable. For instance, we can transform something in millimeters to being in centimeters by dividing it by 10. We could transform a `height` variable into `height above/below 2 meters` variable by subtracting 2 meters from it.   \n\nA couple of common transformations we have seen already are 'centering' and 'standardising':  \n\n- When we \"center\" a variable, we subtracting some number (often the mean of the variable) from every value. So if we 'mean-center' a variable measuring height in cm, and the mean height of my sample is 175cm, then a value of 190 becomes +15, and a value of 150 becomes -25, and so on.  \n- When we 'standardise' a variable, we mean-center it and then divide the resulting values by the standard deviation. So if the standard deviation of heights in my sample is 15, then the value of 190 becomes $\\frac{190-175}{15} = \\frac{15}{15} = 1$, and the 150 becomes $\\frac{150-175}{15} = \\frac{-25}{15} = -1.67$.  \n\nHow does this choice affect the linear models we might be fitting? The short answer is that it doesn't! The overall fit of `lm()` is not changed in any way when we apply these linear^[the fit of models _does_ change if we apply a non-linear transformation, such as $x^2$, $log(x)$, etc., and this can sometimes be useful for studying effects that are more likely to be non-linear!] transformations to predictors or outcomes. \n\nHowever, transformations _do_ change what we get out of our model:  \n\n- If we re-center a predictor on some new value (such as the mean), then all this does is change what \"zero\" means in our variable. This means that if we re-center a predictor in our linear model, the only thing that changes is our intercept. This is because the intercept is \"when all predictors are zero\". And we are changing what \"zero\" represents! \n- When we scale a predictor, this will change the slope. Why? Because it changes what \"moving 1\" represents. So if we standardise a variable, it changes both the intercept and the slope. However, note that the significance of the slope remains _exactly the same_, we are only changing the *units* that we are using to expressing that slope.\n\nThe example below shows a model of heart rates (`HR`) predicted by hours slept (`hrs_sleep`). In @fig-scalexlm you can see our original model (top left), and then various transformations applied to our predictor. Note how these transformations don't affect the model itself - the regression line (and the uncertainty in the line) is the same in each plot. We can see that re-centering changes what the intercept represents:  \n\n- In the top left plot, \"0\" represents zero hours slept, so the intercept (big blue dot) is the estimated heart rate for someone who didn't sleep at all. \n- Similarly, in the top right plot, \"0\" now represents the mean hours slept, so the intercept is the heart rate for someone who slept an average amount, and in the bottom right plot, \"0\" now represents 8 hours of sleep (the recommended amount).\n- In the bottom left plot (where hours slept is 'standardized'), not only have we changed what \"0\" represents, but we have changed what moving \"1\" represents. Rather being an increase of 1 hour of sleep, in this plot it represents an increase of 1 standard deviation hours sleep (whatever that is for our sample - it looks to be about 2.5). This means our estimated slope is the change in heart rate when having 1 SD more hours sleep (approx 2.5).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Centering and scaling predictors in linear regression models. Intercepts and their interpretation change when re-centered, and slope coefficients and their interpretation change when scaling, but the overall model stays the same.](10_centering_files/figure-html/fig-scalexlm-1.png){#fig-scalexlm fig-align='center' width=100%}\n:::\n:::\n\n\nThe thing to note is that the lines themselves are all the same, because the models are all exactly the same. We can prove this to ourselves by comparing the 4 models: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nhrdat <- read_csv(\"https://uoepsy.github.io/data/usmr_hrsleep.csv\")\n\n# original model:\nmod_orig <- lm(HR ~ hrs_sleep, data = hrdat)\n# model with hrs_sleep mean centered\nmod_mc <- lm(HR ~ scale(hrs_sleep, scale=FALSE), data = hrdat)\n# model with hrs_sleep standardised\nmod_z <- lm(HR ~ scale(hrs_sleep), data = hrdat)\n# model with hrs_sleep centered on 8 hours the I() function\n# is a handy function that is just needed because the symbols\n# + and - normally get interprted in lm() as adding \n# and removing predictors. \nmod_8 <- lm(HR ~ I(hrs_sleep-8), data = hrdat) \n\n# all models are identical fit\nanova(mod_orig, mod_mc, mod_z, mod_8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: HR ~ hrs_sleep\nModel 2: HR ~ scale(hrs_sleep, scale = FALSE)\nModel 3: HR ~ scale(hrs_sleep)\nModel 4: HR ~ I(hrs_sleep - 8)\n  Res.Df    RSS Df   Sum of Sq F Pr(>F)\n1     68 3524.5                        \n2     68 3524.5  0 -4.5475e-13         \n3     68 3524.5  0  0.0000e+00         \n4     68 3524.5  0  0.0000e+00         \n```\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n#### Centering when we have interactions\n\nWhen we have an interactions in a model such as `lm(y~x+z+x:z)`, the individual coefficients for `x` and `z` are specifically the associations \"when the other variable included in the interaction is zero\". Because re-centering a variable changes the meaning of \"zero\", this means that these two coefficients will change.  \n\nFor instance, a model of heart rates (`HR`) that includes an interaction between `hrs_sleep` and whether someone smokes, our coefficient for `smoke` estimates the difference in HR between smokers vs non-smokers who get zero hours of sleep (red to blue point in the left-hand plot of @fig-intcent). If we mean-center the `hrs_sleep` variable in our model, then it becomes the estimated difference in HR between smokers vs non-smokers who get the average hours of sleep (red to blue point in the right-hand plot of @fig-intcent). \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![mean-centering a variable that is involved in an interaction will change the point at which the marginal effect of other variable is estimated at](10_centering_files/figure-html/fig-intcent-1.png){#fig-intcent fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Centering predictors in multilevel models\n\nIn multilevel models, things can be a little bit different. \n\n::::{.columns}\n:::{.column width=\"65%\"}\n\nFor one thing, there can be practical benefits to centering and/or scaling predictors with respect to actually *fitting* these models. Because multilevel models involve estimating group-level variability in intercepts and slopes, if our intercept is very far away from our data (e.g., if all our data is from ages 60 to 80, and we are estimating variability at age 0), then slight changes in a slope can have huge influences on estimated intercepts, resulting in models that don't converge. We can see from the longitudinal example ([Chapter 5](05_long.html#modelling-change-over-time){target=\"_blank\"}), with the idea represented in @fig-centconv - using raw `age` values the intercepts and slopes are highly correlated and the model won't converge, but when we recenter the `age` variable on 60 and the intercept variation would become the variability in peoples' cognition _at the start of the study period_, and the random intercepts are not so determined by the random slopes.  \n:::\n\n:::{.column width=\"35%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![lines indicate predicted values from the model with random intercepts and random slopes of age. Due to how age is coded, the 'intercept' is estimated back at age 0](10_centering_files/figure-html/fig-centconv-1.png){#fig-centconv fig-align='center' width=80%}\n:::\n:::\n\n:::\n::::\n\nHowever, in some cases (typically in observational, rather than experimental studies), having multi-level data may mean that we can actually transform a predictor in a couple of ways - we can center it on a constant number like the overall mean/min/max, but we can also consider transformations _within each group_. The key here is that we don't always have just have _one_ \"overall\" mean for a predictor, but often we have different means for each group.  \n\n### Group mean centering\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n:::frame\n__Dataset: lmm_bflpe.csv__\n\nThese data are simulated based on the [\"Big-fish-little-pond\" effect](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6124391/){target=\"_blank\"} in educational literature. \n\nWe are interested in better understanding the relationship between school children's grades and their academic self-concept (their self-perception of ability in specific and general academic disciplines).  \n\nWe have data from 20 classes of children, capturing information on their grades at school (range 0 to 10), and a measure of academic self-concept:  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbfdat <- read_csv(\"https://uoepsy.github.io/data/lmm_bflpe.csv\")\nhead(bfdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  grade class self_concept child\n  <dbl> <dbl>        <dbl> <dbl>\n1  5.14     1         1.54     1\n2  5.3      1         3.62     2\n3  3.91     1        -0.65     3\n4  4.48     1        -0.93     4\n5  5        1         0.28     5\n6  5.32     1         2.36     6\n```\n:::\n:::\n\n\n:::\n\nIn initial exploratory plots, we can see that there is plenty of variation in childrens' grades - we have children scoring 3-4, all the way up to scoring almost 9. Note also, however, that the class's average grades also vary substantially. For instance, classes 8,9,10 and 11 all have a very high average grade.  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(patchwork)\nggplot(bfdat, aes(x=grade,y=self_concept))+\n  geom_point(alpha=.2) +\n\nggplot(bfdat,aes(x=class,y=grade))+\n  geom_jitter(height=0,width=.1,alpha=.2)+\n  stat_summary(geom=\"pointrange\")+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](10_centering_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nWhen we plot the individual childrens' score of 'self-concept' against grades, the picture becomes a bit clearer once we separate by the classes, where we can see that *within each class* there is a fairly positive trend.  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(bfdat,aes(x=grade,y=self_concept))+\n  geom_point(size=2,alpha=.4) +\n\nggplot(bfdat,aes(x=grade,y=self_concept))+\n  geom_point(size=2,alpha=.4)+\n  facet_wrap(~class)\n```\n\n::: {.cell-output-display}\n![](10_centering_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nBy contrast, the relationship between children's self-concept scores and the *average grade of their class* shows a different pattern:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nbfdat <- \n  bfdat |> \n    group_by(class) |>\n    mutate(\n      grade_avg = mean(grade)\n    )\nggplot(bfdat,aes(x=grade_avg,y=self_concept))+\n  stat_summary(geom=\"pointrange\")+\n  labs(x=\"class average grade\")\n```\n\n::: {.cell-output-display}\n![](10_centering_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nSo there are clearly two different things going on here!  \n\n1. We have a positive association between a children's grades _relative to their peers' grades_ and their self-concept. This maybe makes sense - comparisons with other people around you will influence your feelings of self worth. \n2. We almost see a *negative* association between the average grade of a child's class and the child's self-concept --- i.e., children from classes with high grades tend to have slightly _lower_ self-concept!\n\nIn the typical multilevel model that we might fit for this study (below), we just get out one single effect estimate, which represents the expected change in self-concept when a child's grade increases by 1. But we have just seen how a child's grades are driven by two things - their class as a whole, and their relative standing in their class.  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrsmod <- lmer(self_concept ~ grade + (1 + grade | class),\n              data = bfdat)\nsummary(rsmod)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) -17.5685     1.8579  -9.456\ngrade         2.9327     0.3462   8.471\n```\n:::\n:::\n\n\nWhat we want to do here is separate out effects that are \"within\" (i.e. having higher/lower grades *than your classmates*) from those that are \"between\" (i.e. being from a class with higher/lower grades than other classes). To get at these two effects, we are going to explicitly separate our predictor variable into two different parts: \n\n1. the group average\n2. individual deviations from the group average. \n\nWe can calculate these by first using `group_by()` to make the calculations be applied separately for each class, and then calculating the `mean()` grade (for each class), and the deviations for each child from their class's average:  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbfdat <- \n  bfdat |> \n  group_by(class) |>\n  mutate(\n    grade_avg = mean(grade),\n    grade_dev = grade - mean(grade)\n  )\n\nhead(bfdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   class [1]\n  grade class self_concept child grade_avg grade_dev\n  <dbl> <dbl>        <dbl> <dbl>     <dbl>     <dbl>\n1  5.14     1         1.54     1      4.78     0.357\n2  5.3      1         3.62     2      4.78     0.517\n3  3.91     1        -0.65     3      4.78    -0.873\n4  4.48     1        -0.93     4      4.78    -0.303\n5  5        1         0.28     5      4.78     0.217\n6  5.32     1         2.36     6      4.78     0.537\n```\n:::\n:::\n\n\nNote that the actual grade for each child can still be made from our two new columns, calculated as the `avg_grade + grade_dev`.  \n\nSo let's plot the association between each of these new variables and the self-concept scores:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(bfdat, aes(x=grade_avg, y=self_concept))+\n  geom_point() +\n  geom_smooth(method=\"lm\") +\n\nggplot(bfdat, aes(x=grade_dev, y=self_concept))+\n  geom_point() +\n  geom_smooth(method=\"lm\")\n```\n\n::: {.cell-output-display}\n![](10_centering_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nSo we can see that there are two different things going on here - the effect on self-concept of being in a high-performing class, as well as the effect of performing higher _for your class_.  \n\n\n## The within-between model\n\nNow that we have split up the variable grade into two parts (group average, and deviations-from-group-averages), we can actually put these in as separate predictors into our model!  \n\nThis type of model is sometimes referred to as a \"within-between\" model. You can see below both the standard model with random slopes, and the 'within-between' model, in both `lmer()` syntax and in equation form.  \n\nNote that we while we replace one predictor (`x`) with its two constituent parts (the group means of `x` and the deviations from those group means), it is only the within effect that we can have a random slope for. This will hopefully make sense when we think a little about it, because the group-means are \"between groups\" - having a random slope of `group_mean_x|group` is similar to the idea of `handedness|person`, because for a single group, we don't have \"an effect on y of that group having a high average x\", so we can't consider it to be an effect that varies by-group.  \n\n\n\n::::panelset\n:::panel\n#### random slopes model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlmer(y ~ 1 + x + (1 + x | g), data)\n```\n:::\n\n\n$$\n\\begin{align}\n\\text{For observation }j&\\text{ in cluster }i \\\\\n\\text{Level 1:}& \\\\\ny_{ij} &= b_{0i} + b_{1i} \\cdot x_{ij} + \\varepsilon_{ij} \\\\\n\\text{Level 2:}& \\\\\nb_{0i} &= \\gamma_{00} + \\zeta_{0i} \\\\\nb_{1i} &= \\gamma_{10} + \\zeta_{1i} \\\\\n& \\qquad \\\\\n\\text{Where:}& \\\\\n& \\begin{bmatrix} \\zeta_{0i} \\\\ \\zeta_{1i} \\end{bmatrix}\n\\sim N\n\\left(\n    \\begin{bmatrix} 0 \\\\ 0 \\end{bmatrix},\n    \\begin{bmatrix}\n        \\sigma_0 & \\rho_{01} \\\\\n        \\rho_{01} & \\sigma_1\n    \\end{bmatrix}\n\\right) \\\\\n&\\varepsilon_{ij} \\sim N(0,\\sigma_\\varepsilon) \\\\\n\\end{align}\n$$\n:::\n\n:::panel\n#### within-between model  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- data |>\n  group_by(g) |>\n  mutate(\n    x_avg = mean(x),\n    x_dev = x - mean(x)\n  )\n\nlmer(y ~ 1 + x_dev + x_avg + (1 + x_dev | g), data)\n```\n:::\n\n\n$$\n\\begin{align}\n\\text{For observation }j&\\text{ in cluster }i \\\\\n\\text{Level 1:}& \\\\\ny_{ij} &= b_{0i} + b_{1i} \\cdot (x_{ij} - \\bar{x}_i) + b_{2} \\cdot \\bar{x}_i + \\varepsilon_{ij} \\\\\n\\text{Level 2:}& \\\\\nb_{0i} &= \\gamma_{00} + \\zeta_{0i} \\\\\nb_{1i} &= \\gamma_{10} + \\zeta_{1i} \\\\\n& \\qquad \\\\\n\\text{Where:}& \\\\\n& \\begin{bmatrix} \\zeta_{0i} \\\\ \\zeta_{1i} \\end{bmatrix}\n\\sim N\n\\left(\n    \\begin{bmatrix} 0 \\\\ 0 \\end{bmatrix},\n    \\begin{bmatrix}\n        \\sigma_0 & \\rho_{01} \\\\\n        \\rho_{01} & \\sigma_1\n    \\end{bmatrix}\n\\right) \\\\\n&\\varepsilon_{ij} \\sim N(0,\\sigma_\\varepsilon) \\\\\n\\end{align}\n$$\n:::\n::::\n\n<br>    \nIn the context of our educational study of grades and self-concept in school children, we can fit a model that disaggregates within (grade relative to class) and between (class average grade) effects:    \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwbmod <- lmer(self_concept ~ grade_dev + grade_avg + \n                (1 + grade_dev|class), \n              data = bfdat)\n```\n:::\n\n\nThe fixed effects from this model (below) now show two effects, as opposed to only one that we would get from our typical model:   \n\n::::{.columns}\n:::{.column width=\"50%\"}\n__typical random slopes model__\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"zxfkbbhudq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zxfkbbhudq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zxfkbbhudq thead, #zxfkbbhudq tbody, #zxfkbbhudq tfoot, #zxfkbbhudq tr, #zxfkbbhudq td, #zxfkbbhudq th {\n  border-style: none;\n}\n\n#zxfkbbhudq p {\n  margin: 0;\n  padding: 0;\n}\n\n#zxfkbbhudq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zxfkbbhudq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zxfkbbhudq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zxfkbbhudq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zxfkbbhudq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zxfkbbhudq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zxfkbbhudq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zxfkbbhudq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zxfkbbhudq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zxfkbbhudq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zxfkbbhudq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zxfkbbhudq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zxfkbbhudq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zxfkbbhudq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zxfkbbhudq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zxfkbbhudq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zxfkbbhudq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zxfkbbhudq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zxfkbbhudq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zxfkbbhudq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zxfkbbhudq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zxfkbbhudq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zxfkbbhudq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zxfkbbhudq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zxfkbbhudq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zxfkbbhudq .gt_left {\n  text-align: left;\n}\n\n#zxfkbbhudq .gt_center {\n  text-align: center;\n}\n\n#zxfkbbhudq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zxfkbbhudq .gt_font_normal {\n  font-weight: normal;\n}\n\n#zxfkbbhudq .gt_font_bold {\n  font-weight: bold;\n}\n\n#zxfkbbhudq .gt_font_italic {\n  font-style: italic;\n}\n\n#zxfkbbhudq .gt_super {\n  font-size: 65%;\n}\n\n#zxfkbbhudq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zxfkbbhudq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zxfkbbhudq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zxfkbbhudq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zxfkbbhudq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zxfkbbhudq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zxfkbbhudq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zxfkbbhudq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zxfkbbhudq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-17.57</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">1.86</td>\n<td headers=\"t\" class=\"gt_row gt_right\">-9.46</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade</td>\n<td headers=\"est\" class=\"gt_row gt_right\">2.93</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.35</td>\n<td headers=\"t\" class=\"gt_row gt_right\">8.47</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n__within-between model__  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"mlromhosww\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mlromhosww table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mlromhosww thead, #mlromhosww tbody, #mlromhosww tfoot, #mlromhosww tr, #mlromhosww td, #mlromhosww th {\n  border-style: none;\n}\n\n#mlromhosww p {\n  margin: 0;\n  padding: 0;\n}\n\n#mlromhosww .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mlromhosww .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mlromhosww .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mlromhosww .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mlromhosww .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mlromhosww .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlromhosww .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mlromhosww .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mlromhosww .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mlromhosww .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mlromhosww .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mlromhosww .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mlromhosww .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mlromhosww .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mlromhosww .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mlromhosww .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mlromhosww .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mlromhosww .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mlromhosww .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlromhosww .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mlromhosww .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mlromhosww .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mlromhosww .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlromhosww .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mlromhosww .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mlromhosww .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlromhosww .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlromhosww .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mlromhosww .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlromhosww .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mlromhosww .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlromhosww .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mlromhosww .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlromhosww .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mlromhosww .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlromhosww .gt_left {\n  text-align: left;\n}\n\n#mlromhosww .gt_center {\n  text-align: center;\n}\n\n#mlromhosww .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mlromhosww .gt_font_normal {\n  font-weight: normal;\n}\n\n#mlromhosww .gt_font_bold {\n  font-weight: bold;\n}\n\n#mlromhosww .gt_font_italic {\n  font-style: italic;\n}\n\n#mlromhosww .gt_super {\n  font-size: 65%;\n}\n\n#mlromhosww .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mlromhosww .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mlromhosww .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mlromhosww .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mlromhosww .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mlromhosww .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mlromhosww .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mlromhosww .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mlromhosww div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.46</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">1.83</td>\n<td headers=\"t\" class=\"gt_row gt_right\">1.89</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade_dev</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.11</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.35</td>\n<td headers=\"t\" class=\"gt_row gt_right\">8.97</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade_avg</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.69</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.30</td>\n<td headers=\"t\" class=\"gt_row gt_right\">-2.33</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n::::\n\n- the \"within\" effect: for every one grade higher a child is *relative to their classmates*, their self-concept is expected to increase by 3.11.\n- the \"between\" effect: for every 1 grade higher a class average is (and when a child's relative standing in the class stays constant), a child's self-concept is expected to decrease by -0.69.\n\nSo what exactly does the effect (the estimate of 2.93) from our more traditional model show here? Is it the within effect or the between effect? It's actually a smushing together of both parts - it is the estimated effect on self-concept when a child's grade increases by 1, but it is confounded by the fact that as childrens' grades increase then their class average increases a bit too, meaning that the between effect pulls this back down. In short - it's not actually a very useful estimate for us at all, because it conflates the two different effects. \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n## Optional: contextual effects and the mundlak model\n\nAlong with the within-between model, we could also choose to adjust for the group averages while continuing to use the original raw predictor in the model. This is often called the \"Mundlak model\" in reference to [Yair Mundlak](https://doi.org/10.2307/1913646){target=\"_blank\"} who wrote about it in the context of avoiding group-level confounding (see [Chapter 9 #optional-extra-group-confounding](09_assump.html#optional-extra-group-confounding-and-the-random-effects-assumption){target=\"_blank\"}).\n\nThe formulation is very similar to the within-between model, but we don't use the \"deviations from group means\", we simply use the original predictor along with the group means:  \n\n\n::::panelset\n:::panel\n#### within-between model  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- data |>\n  group_by(g) |>\n  mutate(\n    x_avg = mean(x),\n    x_dev = x - mean(x)\n  )\n\nlmer(y ~ 1 + x_dev + x_avg + (1 + x_dev | g), data)\n```\n:::\n\n\n$$\n\\begin{align}\n\\text{For observation }j&\\text{ in cluster }i \\\\\n\\text{Level 1:}& \\\\\ny_{ij} &= b_{0i} + b_{1i} \\cdot (x_{ij} - \\bar{x}_i) + b_{2} \\cdot \\bar{x}_i + \\varepsilon_{ij} \\\\\n\\text{Level 2:}& \\\\\nb_{0i} &= \\gamma_{00} + \\zeta_{0i} \\\\\nb_{1i} &= \\gamma_{10} + \\zeta_{1i} \\\\\n& \\qquad \\\\\n\\text{Where:}& \\\\\n& \\begin{bmatrix} \\zeta_{0i} \\\\ \\zeta_{1i} \\end{bmatrix}\n\\sim N\n\\left(\n    \\begin{bmatrix} 0 \\\\ 0 \\end{bmatrix},\n    \\begin{bmatrix}\n        \\sigma_0 & \\rho_{01} \\\\\n        \\rho_{01} & \\sigma_1\n    \\end{bmatrix}\n\\right) \\\\\n&\\varepsilon_{ij} \\sim N(0,\\sigma_\\varepsilon) \\\\\n\\end{align}\n$$\n:::\n:::panel\n#### mundlak model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- data |>\n  group_by(g) |>\n  mutate(\n    x_avg = mean(x)\n  )\n\nlmer(y ~ 1 + x + x_avg + (1 + x | g), data)\n```\n:::\n\n\n$$\n\\begin{align}\n\\text{For observation }j&\\text{ in cluster }i \\\\\n\\text{Level 1:}& \\\\\ny_{ij} &= b_{0i} + b_{1i} \\cdot x_{ij} + b_{2} \\cdot \\bar{x}_i + \\varepsilon_{ij} \\\\\n\\text{Level 2:}& \\\\\nb_{0i} &= \\gamma_{00} + \\zeta_{0i} \\\\\nb_{1i} &= \\gamma_{10} + \\zeta_{1i} \\\\\n& \\qquad \\\\\n\\text{Where:}& \\\\\n& \\begin{bmatrix} \\zeta_{0i} \\\\ \\zeta_{1i} \\end{bmatrix}\n\\sim N\n\\left(\n    \\begin{bmatrix} 0 \\\\ 0 \\end{bmatrix},\n    \\begin{bmatrix}\n        \\sigma_0 & \\rho_{01} \\\\\n        \\rho_{01} & \\sigma_1\n    \\end{bmatrix}\n\\right) \\\\\n&\\varepsilon_{ij} \\sim N(0,\\sigma_\\varepsilon) \\\\\n\\end{align}\n$$\n:::\n::::\n\n<br>\nWe can fit the Mundlak formulation to our grades & self-concept data as follows:  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmlakmod <- lmer(self_concept ~ grade + grade_avg + \n                  (1 + grade|class), \n                data = bfdat)\n```\n:::\n\n\nThere are two things to note here when comparing the Mundlak formulation to the 'within-between' model. Firstly, these two models provide the same 'within' effect (the fixed effects of `grade_dev` and `grade` in the tables below), because they both get the effect of a child's grade increasing by 1, while holding their class's average grade constant.^[when we exclude the random intercepts, the within-effects from both models are numerically identical, but there may be small differences due to the random slopes of `x|g` for the mundlak model and `x_dev|g` for the within-between model] Secondly, the estimated effects for the `grade_avg` predictor differ substantially between the two models: \n\n::::{.columns}\n:::{.column width=\"50%\"}\n__Within-between model__  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"lkbkbjaewz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lkbkbjaewz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lkbkbjaewz thead, #lkbkbjaewz tbody, #lkbkbjaewz tfoot, #lkbkbjaewz tr, #lkbkbjaewz td, #lkbkbjaewz th {\n  border-style: none;\n}\n\n#lkbkbjaewz p {\n  margin: 0;\n  padding: 0;\n}\n\n#lkbkbjaewz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lkbkbjaewz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lkbkbjaewz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lkbkbjaewz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lkbkbjaewz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lkbkbjaewz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lkbkbjaewz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lkbkbjaewz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lkbkbjaewz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lkbkbjaewz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lkbkbjaewz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lkbkbjaewz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lkbkbjaewz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lkbkbjaewz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lkbkbjaewz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lkbkbjaewz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lkbkbjaewz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lkbkbjaewz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lkbkbjaewz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lkbkbjaewz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lkbkbjaewz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lkbkbjaewz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lkbkbjaewz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lkbkbjaewz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lkbkbjaewz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lkbkbjaewz .gt_left {\n  text-align: left;\n}\n\n#lkbkbjaewz .gt_center {\n  text-align: center;\n}\n\n#lkbkbjaewz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lkbkbjaewz .gt_font_normal {\n  font-weight: normal;\n}\n\n#lkbkbjaewz .gt_font_bold {\n  font-weight: bold;\n}\n\n#lkbkbjaewz .gt_font_italic {\n  font-style: italic;\n}\n\n#lkbkbjaewz .gt_super {\n  font-size: 65%;\n}\n\n#lkbkbjaewz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lkbkbjaewz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lkbkbjaewz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lkbkbjaewz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lkbkbjaewz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lkbkbjaewz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lkbkbjaewz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lkbkbjaewz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lkbkbjaewz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.46</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">1.83</td>\n<td headers=\"t\" class=\"gt_row gt_right\">1.89</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade_dev</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.11</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.35</td>\n<td headers=\"t\" class=\"gt_row gt_right\">8.97</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade_avg</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.69</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.30</td>\n<td headers=\"t\" class=\"gt_row gt_right\">-2.33</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n__Mundlak model__  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"waogcswfzx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#waogcswfzx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#waogcswfzx thead, #waogcswfzx tbody, #waogcswfzx tfoot, #waogcswfzx tr, #waogcswfzx td, #waogcswfzx th {\n  border-style: none;\n}\n\n#waogcswfzx p {\n  margin: 0;\n  padding: 0;\n}\n\n#waogcswfzx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#waogcswfzx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#waogcswfzx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#waogcswfzx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#waogcswfzx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#waogcswfzx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#waogcswfzx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#waogcswfzx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#waogcswfzx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#waogcswfzx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#waogcswfzx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#waogcswfzx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#waogcswfzx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#waogcswfzx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#waogcswfzx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waogcswfzx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#waogcswfzx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#waogcswfzx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#waogcswfzx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waogcswfzx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#waogcswfzx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waogcswfzx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#waogcswfzx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waogcswfzx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#waogcswfzx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#waogcswfzx .gt_left {\n  text-align: left;\n}\n\n#waogcswfzx .gt_center {\n  text-align: center;\n}\n\n#waogcswfzx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#waogcswfzx .gt_font_normal {\n  font-weight: normal;\n}\n\n#waogcswfzx .gt_font_bold {\n  font-weight: bold;\n}\n\n#waogcswfzx .gt_font_italic {\n  font-style: italic;\n}\n\n#waogcswfzx .gt_super {\n  font-size: 65%;\n}\n\n#waogcswfzx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#waogcswfzx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#waogcswfzx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#waogcswfzx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#waogcswfzx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#waogcswfzx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#waogcswfzx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#waogcswfzx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#waogcswfzx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.28</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">2.21</td>\n<td headers=\"t\" class=\"gt_row gt_right\">1.48</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade</td>\n<td headers=\"est\" class=\"gt_row gt_right\">3.10</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.34</td>\n<td headers=\"t\" class=\"gt_row gt_right\">9.12</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">grade_avg</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-3.67</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.34</td>\n<td headers=\"t\" class=\"gt_row gt_right\">-10.91</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n::::\n\n\nThe difference here is that they are capturing two distinct effects. The within-between formulation captures a 'between effect' and the Mundlak formulation provides something that gets termed the \"contextual effect\".  \n\nThe key thing to distinguish between these two is to think about what is being \"held constant\".\nIn the within-between model, the effect of `avg_grade` is estimated while holding constant the child's _relative standing_ in the group. In the Mundlak model, the effect is estimated while holding constant a child's _actual_ grade.  \n\nIt may help to think about this in terms of a single child. Suppose we have a child who has a grade of 5.14, from a class with an average of 4.783. So that child is 0.357 _above their class average._  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n# Groups:   class [1]\n  class child grade_avg grade_dev self_concept\n  <chr> <chr>     <dbl>     <dbl> <chr>       \n1 i     j          4.78     0.357 y           \n```\n:::\n:::\n\n\nBoth models are estimating \"what would we expect to happen to the child's self-concept if their class had an average of 5.783 instead?\"  \n\nThe within-between model estimates this but holds constant the child's deviation above the average, so we're comparing the scenario where the child is 0.357 above a class average of 5.783, as opposed to being 0.357 above a class average of 4.783.\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n# Groups:   class [1]\n  class child grade_avg grade_dev grade self_concept\n  <chr> <chr>     <dbl>     <dbl> <dbl> <chr>       \n1 i     j          4.78     0.357  5.14 y           \n2 i     j          5.78     0.357  6.14 y-0.69      \n```\n:::\n:::\n\n\nBy contrast, the Mundlak model holds constant the child's _actual_ grade, meaning that we're comparing the scenario where the child has a grade of 5.14 and is in a class with an average of 5.783, as opposed to having that same grade of 5.14 but being in a class with an average of 4.783:  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n# Groups:   class [1]\n  class child grade_avg grade self_concept\n  <chr> <chr>     <dbl> <dbl> <chr>       \n1 i     j          4.78  5.14 y           \n2 i     j          5.78  5.14 y-3.67      \n```\n:::\n:::\n\n\nWe can think of this visually. Take a given child from a given class, and think about what would happen if their whole class average grade increased by 1. In @fig-mlak, the red line is \"class 1\" in our data, and the blue line is a counterfactual world of \"class 1 if its average grade increased by 1\". The large red dot represents the expected self-concept for \"child 1\".  \n\nIn the within-between model, we're estimating the self-concept difference for a child between the red (actual) and blue (counterfactual class with a higher average), but where the child stays the same amount \"above average\" in this counterfactual class. In the Mundlak model, we're estimating the self-concept difference when a child stays at the same grade but is in a different context (is placed in a class where the average is 1 higher).  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n        11         12         13         14         15         16         17 \n-0.6887448 -0.6887448 -0.6887448 -0.6887448 -0.6887448 -0.6887448 -0.6887448 \n        18         19         20 \n-0.6887448 -0.6887448 -0.6887448 \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n        11         12         13         14         15         16         17 \n-0.5562254 -0.5562254 -0.5562254 -0.5562254 -0.5562254 -0.5562254 -0.5562254 \n        18         19         20 \n-0.5562254 -0.5562254 -0.5562254 \n```\n:::\n\n::: {.cell-output-display}\n![These plots show an actual class (red) and the counterfactual scenario (blue) where the class average is 1 higher. The large dots show comparisons between a given child in these scenarios - the left-hand plot shows the child's relative standing in the group staying the same (the within-between model estimates this), and the right-hand plot shows the child's raw value staying the same (this is what the Mundlak model estimates)](10_centering_files/figure-html/fig-mlak-1.png){#fig-mlak fig-align='center' width=100%}\n:::\n:::\n",
    "supporting": [
      "10_centering_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}